FROM openjdk:24-oraclelinux9
WORKDIR /app

COPY target/lunchtech-0.0.1-SNAPSHOT.jar /app/lunchtech-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "lunchtech-0.0.1-SNAPSHOT.jar"]

--adicionar a compilação do projeto.